FROM mysql:5.7

LABEL  mantainer="Jounet" \
			descripton="sql" \
			version="1.0"

# Add a database
ENV MYSQL_DATABASE Inventary

# Copy Scripts SQL to Docker
ADD https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md /docker-entrypoint-initdb.d/